const ingredientCategories = {
  Meat: [
    "beef",
    "pork",
    "chicken",
    "turkey",
    "lamb",
    "duck",
    "bacon",
    "ham",
    "sausage",
    "venison",
    "fish",
    "salmon",
    "tuna",
    "shrimp",
    "crab",
    "lobster",
    "steak",
  ],
  Veggies: [
    "lettuce",
    "spinach",
    "carrot",
    "broccoli",
    "cauliflower",
    "kale",
    "tomato",
    "cucumber",
    "pepper",
    "zucchini",
    "eggplant",
    "asparagus",
    "onion",
    "garlic",
    "mushroom",
    "potato",
    "sweet potato",
  ],
  Bread: ["bread", "flour", "yeast", "bagel", "bun", "roll", "sourdough"],
  Desserts: [
    "chocolate",
    "sugar",
    "cream",
    "butter",
    "honey",
    "vanilla",
    "cake",
    "cupcake",
    "cookie",
    "brownie",
    "pie",
    "pastry",
  ],
  Keto: [
    "almond flour",
    "coconut flour",
    "stevia",
    "avocado",
    "cheese",
    "cauliflower",
    "zucchini",
    "chicken",
  ],
};

module.exports = ingredientCategories;
